### ISSUE TITLE
Failing at parsing multiple collections

### ISSUE THREAD

**Issue by palexdev** [jonas-grgt/xjx#12]
I'm having issues parsing an XML file with this structure
```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
   <foo name="A"/>
  <foo name="B"/>
			 
  <bar name="X">
    <info val="InfoValX1"/>
    <info val="InfoValX2"/>
</bar>
<bar name="Z">
    <info val="InfoValZ1"/>
</bar>
</manifest>
```

I set up a JUnit test too to reproduce the issue
```java
public class XjXTests {

	@Test
	void testMultipleListsDeserialization() {
		String data = """
			<?xml version="1.0" encoding="UTF-8"?>
			<manifest>
			 <foo name="A"/>
			 <foo name="B"/>
			 
			 <bar name="X">
			     <info val="InfoValX1"/>
			     <info val="InfoValX2"/>
			 </bar>
			 <bar name="Z">
			     <info val="InfoValZ1"/>
			 </bar>
			</manifest>
			""";
		XjxSerdes xjx = new XjxSerdes();
		Manifest manifest = xjx.read(data, Manifest.class);

		System.out.println(manifest.foos);
		System.out.println(manifest.bars);

		assertNotNull(manifest.foos);
		assertNotNull(manifest.bars);
	}

	private static class Manifest {
		@Tag(path = "/manifest", items = "foo")
		private List<Foo> foos;

		@Tag(path = "/manifest", items = "bar")
		private List<Bar> bars;
	}

	private static class Foo {
		@Tag(path = "/manifest/foo", attribute = "name")
		private String name;
	}

	private static class Bar {
		@Tag(path = "/manifest/bar", attribute = "name")
		private String name;

		@Tag(path = "/manifest/bar", items = "info")
		private List<Info> infos;
	}

	private static class Info {
		@Tag(path = "/manifest/bar/info", attribute = "val")
		private String val;
	}
}
```

There are actually two issues.
1) The `foos` List is `null`. This is because of the bug (?), I believe XJX fails at parsing multiple collections on the same level
2) The `bars` List is empty, but this is probably an error on my side on defining the model classes. Sorry, it's my first day using your library, and I'm trying to figure out how it works, what it can do

**Comment by jonas-grgt** [comment]
Hi @palexdev, no need to apologize.

I very much appreciate your very detailed bug report. Your are spot on!

You unveiled a couple of issues with xjx:
- it fails at handling multiple collections within the same containing/root tag
- repeated collection don't work as expected

I'll look into those and try to fix them as soon as possible.

**Comment by palexdev** [comment]
Thanks @jonas-grgt 
It's actually a pretty good library, lightweight, easy to use, well documented and straight to the point, I like it
Looking forward to the fixes, have a nice day!

**Comment by jonas-grgt** [comment]
Was able to replicate it and add the necessary code to add fix this bug or add this new functionality, depending on how you look at it.

Release 0.3.3 contains the fix. 

Thanks again @palexdev and if anything else do not hesitate to give feedback, request features or report bugs!

**Comment by palexdev** [comment]
> @palexdev I was wondering if it in the end solve your issue?

Hey @jonas-grgt, sorry for the delay.
To be honest, since I needed my project to be ready asap and since I didn't know you would actually be this fast, I switched to Jakarta.
BUT, to be fair, I still have the XJX dependencies commented in my Gradle config, because I still plan to use XJX as soon as other core functionalities are ready and tested.
I'll let you know eventually, anyway, thanks for your work and the support!
